apiVersion: v1
kind: Service
metadata:
  annotations:
    kurtosistech.com/ports: metrics:8080/TCP/http-2m0s
  creationTimestamp: "2024-11-15T15:41:35Z"
  labels:
    kurtosistech.com/app-id: kurtosis
    kurtosistech.com/enclave-id: b865f733a4e64a10b304c7320ca78ba7
    kurtosistech.com/guid: 4efcb43dce19420f81acc544570ee9f8
    kurtosistech.com/id: vc-3-geth-lodestar
    kurtosistech.com/resource-type: user-service
  name: vc-3-geth-lodestar
  namespace: kt-kurtosis-geth-lodestar
  resourceVersion: "32466326"
  uid: 175850c2-c0e8-40ef-89ac-190d78c5142e
spec:
  clusterIP: 172.23.57.230
  clusterIPs:
  - 172.23.57.230
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: nonexistent-port
    port: 1
    protocol: TCP
    targetPort: 1
  - appProtocol: http
    name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    kurtosistech.com/app-id: kurtosis
    kurtosistech.com/enclave-id: b865f733a4e64a10b304c7320ca78ba7
    kurtosistech.com/guid: 4efcb43dce19420f81acc544570ee9f8
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
