global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.

scrape_configs:
  - job_name: "charon-0"
    static_configs:
      - targets: ["node0:3620"]
  - job_name: "charon-1"
    static_configs:
      - targets: ["node1:3620"]
  - job_name: "charon-2"
    static_configs:
      - targets: ["node2:3620"]
  - job_name: "vc-lighthouse"
    static_configs:
      - targets:
          ["vc0-lighthouse:5064", "vc1-lighthouse:5064", "vc2-lighthouse:5064"]
  - job_name: "vc-teku"
    static_configs:
      - targets: ["vc0-teku:8008", "vc1-teku:8008", "vc2-teku:8008"]
  - job_name: "vc-nimbus"
    static_configs:
      - targets: ["vc0-nimbus:8008", "vc1-nimbus:8008", "vc2-nimbus:8008"]
  - job_name: "vc-lodestar"
    static_configs:
      - targets: ["vc0-lodestar:5064", "vc1-lodestar:5064", "vc2-lodestar:5064"]
  - job_name: "vc-prysm"
    static_configs:
      - targets: ["vc0-prysm:8081", "vc1-prysm:8081", "vc2-prysm:8081"]
  - job_name: "otelcollector"
    static_configs:
      - targets: ["otelcollector:8889"]
