global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.

remote_write:
  - url: https://vm.monitoring.gcp.obol.tech/write
    authorization:
      credentials: ""
    write_relabel_configs:
      - source_labels: [job]
        regex: "charon(.*)"
        action: keep # Keeps charon metrics and drop metrics from other containers.

scrape_configs:
  - job_name: "charon-0"
    static_configs:
      - targets: ["node0:3620"]
  - job_name: "charon-1"
    static_configs:
      - targets: ["node1:3620"]
  - job_name: "charon-2"
    static_configs:
      - targets: ["node2:3620"]
  - job_name: "charon-3"
    static_configs:
      - targets: ["node3:3620"]
  - job_name: "charon-4"
    static_configs:
      - targets: ["node4:3620"]
  - job_name: "charon-5"
    static_configs:
      - targets: ["node5:3620"]
  - job_name: "vc-lighthouse"
    static_configs:
      - targets: ["vc0-lighthouse:5064", "vc1-lighthouse:5064", "vc2-lighthouse:5064"]
  - job_name: "vc-teku"
    static_configs:
      - targets: ["vc0-teku:8008", "vc1-teku:8008", "vc2-teku:8008"]
  - job_name: "vc-nimbus"
    static_configs:
      - targets: ["vc0-nimbus:8008", "vc1-nimbus:8008", "vc2-nimbus:8008"]
  - job_name: "vc-lodestar"
    static_configs:
      - targets: ["vc0-lodestar:5064", "vc1-lodestar:5064", "vc2-lodestar:5064"]
  - job_name: "vc-prysm"
    static_configs:
      - targets: ["vc0-prysm:8081", "vc1-prysm:8081", "vc2-prysm:8081"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
