apiVersion: v1
kind: Service
metadata:
  annotations:
    kurtosistech.com/ports: metrics:8080/TCP/http-2m0s
  creationTimestamp: "2024-11-15T14:46:24Z"
  labels:
    kurtosistech.com/app-id: kurtosis
    kurtosistech.com/enclave-id: a6afd25bcadf447d8ab555a222984163
    kurtosistech.com/guid: affe18a4dffc4a5d90c84288402c0a62
    kurtosistech.com/id: vc-2-geth-lighthouse
    kurtosistech.com/resource-type: user-service
  name: vc-2-geth-lighthouse
  namespace: kt-kurtosis-geth-lighthouse
  resourceVersion: "32447572"
  uid: 7c61a0ec-6da4-460e-ad50-be0799aaa0de
spec:
  clusterIP: 172.23.111.42
  clusterIPs:
  - 172.23.111.42
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: nonexistent-port
    port: 1
    protocol: TCP
    targetPort: 1
  - appProtocol: http
    name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    kurtosistech.com/app-id: kurtosis
    kurtosistech.com/enclave-id: a6afd25bcadf447d8ab555a222984163
    kurtosistech.com/guid: affe18a4dffc4a5d90c84288402c0a62
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
