apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 4288acc226d2314bd20ba68d7c2fc7503e520c9c6bab726819635be577f18c85
    cni.projectcalico.org/podIP: 172.27.222.158/32
    cni.projectcalico.org/podIPs: 172.27.222.158/32
    kurtosistech.com/ports: metrics:8080/TCP/http-2m0s
  creationTimestamp: "2024-11-12T14:31:17Z"
  labels:
    kurtosistech.com.custom/ethereum-package.client: nimbus
    kurtosistech.com.custom/ethereum-package.client-image: statusim-nimbus-validator-client_multiarch-v24.7.0
    kurtosistech.com.custom/ethereum-package.client-type: validator
    kurtosistech.com.custom/ethereum-package.connected-client: nimbus
    kurtosistech.com.custom/ethereum-package.sha256: ""
    kurtosistech.com/app-id: kurtosis
    kurtosistech.com/enclave-id: 6f7c3159698d4f588afc602e94a24380
    kurtosistech.com/guid: 4f2be180b53b4d2b83352c371bc8dde1
    kurtosistech.com/id: vc-1-geth-nimbus
    kurtosistech.com/resource-type: user-service
  name: vc-1-geth-nimbus
  namespace: kt-kurtosis-geth-nimbus
  resourceVersion: "31023081"
  uid: b407755d-45c9-4ceb-8df8-a6a7c71ab0e0
spec:
  containers:
  - args:
    - --beacon-node=http://172.23.46.239:4000
    - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
    - --metrics
    - --metrics-address=0.0.0.0
    - --metrics-port=8080
    - --graffiti=1-geth-nimbus
    - --validators-dir=/validator-keys/nimbus-keys
    - --secrets-dir=/validator-keys/secrets
    - --payload-builder=true
    image: statusim/nimbus-validator-client:multiarch-v24.7.0
    imagePullPolicy: IfNotPresent
    name: user-service-container
    ports:
    - containerPort: 8080
      name: metrics
      protocol: TCP
    resources: {}
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /keymanager
      name: files-artifact-expansion
      subPath: "0"
    - mountPath: /validator-keys
      name: files-artifact-expansion
      subPath: "1"
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r4th8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: SERIALIZED_ARGS
      value: '{"apiContainerIpAddress":"172.23.239.138","apiContainerPort":7443,"filesArtifactExpansions":[{"filesIdentifier":"keymanager_file","dirPathToExpandTo":"/files-artifacts/4872df6c56db424eb791fe8756dcb121"},{"filesIdentifier":"1-nimbus-geth-0-255-0","dirPathToExpandTo":"/files-artifacts/41fd59f95a414f5081f9c69cae98c30e"}]}'
    image: kurtosistech/files-artifacts-expander:1.3.1
    imagePullPolicy: IfNotPresent
    name: files-artifact-expander
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /files-artifacts/4872df6c56db424eb791fe8756dcb121
      name: files-artifact-expansion
      subPath: "0"
    - mountPath: /files-artifacts/41fd59f95a414f5081f9c69cae98c30e
      name: files-artifact-expansion
      subPath: "1"
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r4th8
      readOnly: true
  nodeName: 10.233.130.100
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 120
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 120
  volumes:
  - emptyDir: {}
    name: files-artifact-expansion
  - name: kube-api-access-r4th8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T14:31:21Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T14:31:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T14:31:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T14:31:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T14:31:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e77dee8d61150ca908b8769dfcac2356ed65dd4c20412fa4dcaed3d269e7eadc
    image: docker.io/statusim/nimbus-validator-client:multiarch-v24.7.0
    imageID: docker.io/statusim/nimbus-validator-client@sha256:909f740ab95b1023847d2fdaf8c90a9639d81a18b95e0a6f3818b19fcf28bbbb
    lastState: {}
    name: user-service-container
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-11-12T14:31:26Z"
  hostIP: 10.233.130.100
  hostIPs:
  - ip: 10.233.130.100
  initContainerStatuses:
  - containerID: containerd://36b0069b6d0c7fc2bc575457b8c6c45acfce243c0577142bd9af7872cb15fc13
    image: docker.io/kurtosistech/files-artifacts-expander:1.3.1
    imageID: docker.io/kurtosistech/files-artifacts-expander@sha256:2518bf2d828b47e84f7c7b7f8e28f4e315333e76c68ab78088b5276036e8d00a
    lastState: {}
    name: files-artifact-expander
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://36b0069b6d0c7fc2bc575457b8c6c45acfce243c0577142bd9af7872cb15fc13
        exitCode: 0
        finishedAt: "2024-11-12T14:31:21Z"
        reason: Completed
        startedAt: "2024-11-12T14:31:20Z"
  phase: Running
  podIP: 172.27.222.158
  podIPs:
  - ip: 172.27.222.158
  qosClass: BestEffort
  startTime: "2024-11-12T14:31:17Z"
