// Code generated by "stringer -type BNType -trimprefix BNType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BNTypeLighthouse-0]
	_ = x[BNTypeLodestar-1]
	_ = x[BNTypeNimbus-2]
	_ = x[BNTypePrysm-3]
	_ = x[BNTypeTeku-4]
	_ = x[BNTypeUnknown-5]
}

const _BNType_name = "LighthouseLodestarNimbusPrysmTekuUnknown"

var _BNType_index = [...]uint8{0, 10, 18, 24, 29, 33, 40}

func (i BNType) String() string {
	if i < 0 || i >= BNType(len(_BNType_index)-1) {
		return "BNType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BNType_name[_BNType_index[i]:_BNType_index[i+1]]
}
