// Code generated by "stringer -type CLType -trimprefix CLType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CLTypeLighthouse-0]
	_ = x[CLTypeLodestar-1]
	_ = x[CLTypeNimbus-2]
	_ = x[CLTypePrysm-3]
	_ = x[CLTypeTeku-4]
	_ = x[CLTypeUnknown-5]
}

const _CLType_name = "LighthouseLodestarNimbusPrysmTekuUnknown"

var _CLType_index = [...]uint8{0, 10, 18, 24, 29, 33, 40}

func (i CLType) String() string {
	if i < 0 || i >= CLType(len(_CLType_index)-1) {
		return "CLType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CLType_name[_CLType_index[i]:_CLType_index[i+1]]
}
