// Code generated by "stringer -type ELType -trimprefix ELType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ELTypeGeth-0]
	_ = x[ELTypeUnknown-1]
}

const _ELType_name = "GethUnknown"

var _ELType_index = [...]uint8{0, 4, 11}

func (i ELType) String() string {
	if i < 0 || i >= ELType(len(_ELType_index)-1) {
		return "ELType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELType_name[_ELType_index[i]:_ELType_index[i+1]]
}
